import type { DrawItem } from "../types";

const FLAG_BY_CODE: Record<string, string> = {
  ALGERIA: "🇩🇿",
  ARGENTINA: "🇦🇷",
  AUSTRALIA: "🇦🇺",
  AUSTRIA: "🇦🇹",
  BELGIUM: "🇧🇪",
  BOSNIA_AND_HERZEGOVINA: "🇧🇦",
  BRAZIL: "🇧🇷",
  CABO_VERDE: "🇨🇻",
  CANADA: "🇨🇦",
  COLOMBIA: "🇨🇴",
  CONGO_DR: "🇨🇩",
  CROATIA: "🇭🇷",
  CURACAO: "🇨🇼",
  CZECHIA: "🇨🇿",
  COTE_DIVOIRE: "🇨🇮",
  ECUADOR: "🇪🇨",
  EGYPT: "🇪🇬",
  ENGLAND: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  FRANCE: "🇫🇷",
  GERMANY: "🇩🇪",
  GHANA: "🇬🇭",
  HAITI: "🇭🇹",
  IR_IRAN: "🇮🇷",
  IRAQ: "🇮🇶",
  JAPAN: "🇯🇵",
  JORDAN: "🇯🇴",
  KOREA_REPUBLIC: "🇰🇷",
  MEXICO: "🇲🇽",
  MOROCCO: "🇲🇦",
  NETHERLANDS: "🇳🇱",
  NEW_ZEALAND: "🇳🇿",
  NORWAY: "🇳🇴",
  PANAMA: "🇵🇦",
  PARAGUAY: "🇵🇾",
  PORTUGAL: "🇵🇹",
  QATAR: "🇶🇦",
  SAUDI_ARABIA: "🇸🇦",
  SCOTLAND: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  SENEGAL: "🇸🇳",
  SOUTH_AFRICA: "🇿🇦",
  SPAIN: "🇪🇸",
  SWITZERLAND: "🇨🇭",
  SWEDEN: "🇸🇪",
  TUNISIA: "🇹🇳",
  TÜRKIYE: "🇹🇷",
  USA: "🇺🇸",
  URUGUAY: "🇺🇾",
  UZBEKISTAN: "🇺🇿",
};

const HOME_KITS_BY_CODE: Record<string, { primary: string; secondary: string; text: string }> = {
  ALGERIA: { primary: "#f7f7f2", secondary: "#148143", text: "#111111" },
  ARGENTINA: { primary: "#75aadb", secondary: "#ffffff", text: "#111111" },
  AUSTRALIA: { primary: "#f8c400", secondary: "#115740", text: "#111111" },
  AUSTRIA: { primary: "#ef3340", secondary: "#ffffff", text: "#ffffff" },
  BELGIUM: { primary: "#d00027", secondary: "#fdda24", text: "#ffffff" },
  BOSNIA_AND_HERZEGOVINA: { primary: "#1d4ed8", secondary: "#facc15", text: "#ffffff" },
  BRAZIL: { primary: "#fedd00", secondary: "#009c3b", text: "#111111" },
  CABO_VERDE: { primary: "#003893", secondary: "#ffffff", text: "#ffffff" },
  CANADA: { primary: "#e31b23", secondary: "#ffffff", text: "#ffffff" },
  COLOMBIA: { primary: "#fcd116", secondary: "#003893", text: "#111111" },
  CONGO_DR: { primary: "#00a3e0", secondary: "#f7d618", text: "#111111" },
  CROATIA: { primary: "#ffffff", secondary: "#e32219", text: "#111111" },
  CURACAO: { primary: "#0057b8", secondary: "#f9d616", text: "#ffffff" },
  CZECHIA: { primary: "#d7141a", secondary: "#ffffff", text: "#ffffff" },
  COTE_DIVOIRE: { primary: "#f77f00", secondary: "#009e60", text: "#111111" },
  ECUADOR: { primary: "#ffdd00", secondary: "#034ea2", text: "#111111" },
  EGYPT: { primary: "#ce1126", secondary: "#ffffff", text: "#ffffff" },
  ENGLAND: { primary: "#f7f7f7", secondary: "#cf142b", text: "#111111" },
  FRANCE: { primary: "#1d3557", secondary: "#ffffff", text: "#ffffff" },
  GERMANY: { primary: "#f7f7f7", secondary: "#111111", text: "#111111" },
  GHANA: { primary: "#ffffff", secondary: "#fcd116", text: "#111111" },
  HAITI: { primary: "#00209f", secondary: "#d21034", text: "#ffffff" },
  IR_IRAN: { primary: "#ffffff", secondary: "#239f40", text: "#111111" },
  IRAQ: { primary: "#ce1126", secondary: "#ffffff", text: "#ffffff" },
  JAPAN: { primary: "#003f8f", secondary: "#ffffff", text: "#ffffff" },
  JORDAN: { primary: "#d71920", secondary: "#ffffff", text: "#ffffff" },
  KOREA_REPUBLIC: { primary: "#e6002d", secondary: "#ffffff", text: "#ffffff" },
  MEXICO: { primary: "#006847", secondary: "#ce1126", text: "#ffffff" },
  MOROCCO: { primary: "#c1272d", secondary: "#006233", text: "#ffffff" },
  NETHERLANDS: { primary: "#f58220", secondary: "#21468b", text: "#111111" },
  NEW_ZEALAND: { primary: "#f7f7f7", secondary: "#111111", text: "#111111" },
  NORWAY: { primary: "#ba0c2f", secondary: "#00205b", text: "#ffffff" },
  PANAMA: { primary: "#d21034", secondary: "#ffffff", text: "#ffffff" },
  PARAGUAY: { primary: "#d52b1e", secondary: "#ffffff", text: "#ffffff" },
  PORTUGAL: { primary: "#c8102e", secondary: "#006b3f", text: "#ffffff" },
  QATAR: { primary: "#8a1538", secondary: "#ffffff", text: "#ffffff" },
  SAUDI_ARABIA: { primary: "#006c35", secondary: "#ffffff", text: "#ffffff" },
  SCOTLAND: { primary: "#002b5c", secondary: "#ffffff", text: "#ffffff" },
  SENEGAL: { primary: "#ffffff", secondary: "#00853f", text: "#111111" },
  SOUTH_AFRICA: { primary: "#ffb81c", secondary: "#007a4d", text: "#111111" },
  SPAIN: { primary: "#c60b1e", secondary: "#ffc400", text: "#ffffff" },
  SWITZERLAND: { primary: "#d52b1e", secondary: "#ffffff", text: "#ffffff" },
  SWEDEN: { primary: "#005293", secondary: "#fecb00", text: "#ffffff" },
  TUNISIA: { primary: "#e70013", secondary: "#ffffff", text: "#ffffff" },
  TÜRKIYE: { primary: "#e30a17", secondary: "#ffffff", text: "#ffffff" },
  USA: { primary: "#ffffff", secondary: "#3c3b6e", text: "#111111" },
  URUGUAY: { primary: "#75aadb", secondary: "#111111", text: "#111111" },
  UZBEKISTAN: { primary: "#1eb2e8", secondary: "#ffffff", text: "#111111" },
};

export function flagForItem(item: DrawItem) {
  return FLAG_BY_CODE[item.code] ?? "PO";
}

export function homeKitForItem(item: DrawItem) {
  return HOME_KITS_BY_CODE[item.code] ?? {
    primary: item.primary_color,
    secondary: item.secondary_color,
    text: "#ffffff",
  };
}
